kind: Deployment
apiVersion: apps/v1
metadata:
  name: chrome
  namespace: selenium-grid
  labels:
    app: chrome
spec:
  selector:
    matchLabels:
      app: chrome
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: chrome
    spec:
      containers:
      - env:
        - name: SE_EVENT_BUS_HOST
          value: selenium-event-bus
        - name: SE_EVENT_BUS_PUBLISH_PORT
          value: "4442"
        - name: SE_EVENT_BUS_SUBSCRIBE_PORT
          value: "4443"
        image: selenium/node-chrome:4.4.0-20220812
        imagePullPolicy: ""
        name: chrome
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
