kind: Deployment
apiVersion: apps/v1
metadata:
  name: edge
  namespace: selenium-grid
  labels:
    app: edge
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: edge
  template:
    metadata:
      labels:
        app: edge
    spec:
      containers:
      - env:
        - name: SE_EVENT_BUS_HOST
          value: selenium-event-bus
        - name: SE_EVENT_BUS_PUBLISH_PORT
          value: "4442"
        - name: SE_EVENT_BUS_SUBSCRIBE_PORT
          value: "4443"
        image: selenium/node-edge:4.4.0-20220812
        imagePullPolicy: ""
        name: edge
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
